"""add user smtp fields

Revision ID: 277052e6abc6
Revises: 
Create Date: 2026-08-30 03:58:56.034350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277052e6abc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('smtp_server', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('smtp_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smtp_password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('smtp_from_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('smtp_from_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smtp_use_tls', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('smtp_use_tls')
        batch_op.drop_column('smtp_from_name')
        batch_op.drop_column('smtp_from_email')
        batch_op.drop_column('smtp_password')
        batch_op.drop_column('smtp_username')
        batch_op.drop_column('smtp_port')
        batch_op.drop_column('smtp_server')
        batch_op.drop_column('smtp_enabled')

    # ### end Alembic commands ###
