"""add keyword and ai settings

Revision ID: 9ec2a005067c
Revises: 6db6313773ac
Create Date: 2026-09-01 15:32:36.879693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec2a005067c'
down_revision = '6db6313773ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_risk_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('ai_risk_threshold')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_api_key')
        batch_op.drop_column('ai_provider')
        batch_op.drop_column('alert_mode')

    op.drop_table('keyword_rules')
    # ### end Alembic commands ###
